version: '3'
services:
    caddy:
        build: .
        image: alpine-caddy
        container_name: api-proxy
        ports:
            - "3000:3000"
            - "4000:4000"
        env_file: .env
        volumes:
            - ./Caddyfile:/etc/Caddyfile
            - ./public:/var/www/html
            - ./.caddy:/root/.caddy
